In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error

df = pd.read_csv("student_scores.csv")

print(df.head(10))
#df.plot.scatter(x='Hours',y='Scores',title='Scatter Plot of Hours with Scores',c='r')
print(df.describe())

y = df['Scores'].values.reshape(-1,1)
x = df['Hours'].values.reshape(-1,1)

print(df['Scores'].values)
print(df['Hours'].values.shape)
print(x.shape)
print(x)

#x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
seed = 42
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=seed)

print(x_train)
print(y_train)

model = LinearRegression()
model.fit(x_train,y_train)
print(model.coef_)
print(model.intercept_)

score = model.predict([[5]])
print(score)

y_pred = model.predict(x_test)

df_preds = pd.DataFrame({'Actual':y_test.squeeze(), 'Predicted':y_pred.squeeze()})
print(df_preds)

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)

rmse = np.sqrt(mse)

print(f'Mean Absolute Error : {mae:.2f}')



model.predict([[5]])





   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25
           Hours     Scores
count  25.000000  25.000000
mean    5.012000  51.480000
std     2.525094  25.286887
min     1.100000  17.000000
25%     2.700000  30.000000
50%     4.800000  47.000000
75%     7.400000  75.000000
max     9.200000  95.000000
[21 47 27 75 30 20 88 60 81 25 85 62 41 42 17 95 30 24 67 69 30 54 35 76
 86]
(25,)
(25, 1)
[[2.5]
 [5.1]
 [3.2]
 [8.5]
 [3.5]
 [1.5]
 [9.2]
 [5.5]
 [8.3]
 [2.7]
 [7.7]
 [5.9]
 [4.5]
 [3.3]
 [1.1]
 [8.9]
 [2.5]
 [1.9]
 [6.1]
 [7.4]
 [2.7]
 [4.8]
 [3.8]
 [6.9]
 [7.8]]
[[2.7]
 [3.3]
 [5.1]
 [3.8]
 [1.5]
 [3.2]
 [4.5]
 [8.9]
 [8.5]
 [3.5]
 [2.7]
 [1.9]
 [4.8]
 [6.1]
 [7.8]
 [5.5]
 [7.7]
 [1.1]
 [7.4]
 [9.2]]
[[25]
 [42]
 [47]
 [35]
 [20]
 [27]
 [41]
 [95]
 [75]
 [30]
 [30]
 [24]
 [54]
 [67]
 [86]
 [60]
 [85]
 [17]
 [69]
 [88]]
[[9.68207815]]
[2.82689235]
[[5

array([[51.23728313]])

In [2]:
100-3.92

96.08